FROM node:18-alpine

# Create and set workdir
RUN mkdir -p /opt/frontend
RUN chown -R node:node /opt/frontend
WORKDIR /opt/frontend

# Install nodejs global packages
RUN npm install -g gatsby-cli

# Copy package.json to cache packages image layer
COPY package.json ./
COPY yarn.lock ./

# # Needed for parcel (Which in turn is needed for building gatsby)
RUN apk add --no-cache python3 make g++ && apk add vips-dev fftw-dev --update-cache && rm -fR /var/cache/apk/*

RUN yarn config set network-timeout 1000000 -g 
RUN yarn install --no-cache

# Copy sourcecode files
COPY . .

# Also exposing VSCode debug ports
EXPOSE 8000 9929 9230

CMD gatsby develop --host 0.0.0.0