version: "3.8"

services:
  frontend:
    command: ["gatsby", "develop", "--host", "0.0.0.0"]
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/usr/src/frontend/src
      - /usr/src/frontend/node_modules
    networks:
      - app-network
    environment:
      NODE_ENV: development
      STRAPI_URL: http://backend:1337
      BACKEND_URL: http://backend:1337
      BACKEND_TOKEN: dfa36a27ece762e5381584ba106650e9906cf06ed65cb6ad5000f54b4d68f7c48f4032ce64e04e2a693e11b587cff079761dcf5ac8cc3ea5f9f5c99894f83a7ff887f21c70ab31177d42c2c6ed23a2df8deb9e77bc3a47ae4cdc45b7fac1cefb5aa45c590732f7ef2ad01271db39d897f5fa3ba27c668a4466bd14b954c1bbfb
      FRONTEND_URL: http://localhost:8000
    stdin_open: true
    tty: true
    depends_on:
      - backend
    ports:
      - "8000:8000"
      - "9929:9929"
      - "9230:9230"
  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src/:/usr/src/backend/src
      - /usr/src/backend/node_modules
    networks:
      - app-network
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: B9Hi1jAd9NNenqYN73DPcw==,RNxKP5vjEt1aj4or0wnPEQ==,ORRO8yILNK7CsTdB4rInRQ==,sqvQUngp6cgxPw+ZIuoH/Q==
      API_TOKEN_SALT: cXhrYqY5uVTrfkj/njbouA==
      ADMIN_JWT_SECRET: DdFTXp8yIY3VHfOHUd/Btg==
      TRANSFER_TOKEN_SALT: zLXkayR6XqbEN130yTMDaw==

      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      JWT_SECRET: 1+Nl3cItlLBrAVGDtKSp/g==
      NTBA_FIX_319: 1

      TELEGRAM_TOKEN: 7054787088:AAHd1-1UuWGTwYo3CBOvytMoACve3aGWrJY
      RESEND_API_KEY: re_i9tQfThW_QFc87jisdi8MvWkShrmXarfk
      RESEND_EMAIL: todaywillnotend@gmail.com
      BACKEND_URL: http://backend:1337
      BACKEND_TOKEN: dfa36a27ece762e5381584ba106650e9906cf06ed65cb6ad5000f54b4d68f7c48f4032ce64e04e2a693e11b587cff079761dcf5ac8cc3ea5f9f5c99894f83a7ff887f21c70ab31177d42c2c6ed23a2df8deb9e77bc3a47ae4cdc45b7fac1cefb5aa45c590732f7ef2ad01271db39d897f5fa3ba27c668a4466bd14b954c1bbfb
    ports:
      - "1337:1337"
    restart: always

networks:
  app-network:
    driver: bridge
