version: "3.3"

services:
  reverse-proxy:
    image: nginx:1.17.10
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse_proxy/ssl/:/etc/nginx/ssl/
    ports:
      - 80:80
      - 443:443

  frontend:
    stdin_open: true
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend/src/:/opt/frontend/src
      - ./frontend/gatsby-config.ts:/opt/frontend/gatsby-config.ts
      - ./frontend/scripts/server.js:/opt/frontend/scripts/server.js
      - /opt/frontend/node_modules
    networks:
      - app-network
    environment:
      NODE_ENV: production
      STRAPI_URL: http://158.160.46.88:1337
      GATSBY_BACKEND_URL: https://xn--80ascqaidaiedd.xn--p1ai/backend
      GATSBY_BACKEND_TOKEN: dfa36a27ece762e5381584ba106650e9906cf06ed65cb6ad5000f54b4d68f7c48f4032ce64e04e2a693e11b587cff079761dcf5ac8cc3ea5f9f5c99894f83a7ff887f21c70ab31177d42c2c6ed23a2df8deb9e77bc3a47ae4cdc45b7fac1cefb5aa45c590732f7ef2ad01271db39d897f5fa3ba27c668a4466bd14b954c1bbfb
      GATSBY_FRONTEND_URL: https://158.160.46.88
      ENABLE_GATSBY_REFRESH_ENDPOINT: 1
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend/config:/opt/backend/config
      - ./backend/src:/opt/backend/src
      - ./backend/package.json:/opt/package.json
      - ./backend/yarn.lock:/opt/yarn.lock
      - ./backend/.env:/opt/backend/.env
      - ./backend/public/uploads:/opt/backend/public/uploads
      - ./backend/.tmp:/opt/backend/.tmp
    networks:
      - app-network
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: B9Hi1jAd9NNenqYN73DPcw==,RNxKP5vjEt1aj4or0wnPEQ==,ORRO8yILNK7CsTdB4rInRQ==,sqvQUngp6cgxPw+ZIuoH/Q==
      API_TOKEN_SALT: cXhrYqY5uVTrfkj/njbouA==
      ADMIN_JWT_SECRET: DdFTXp8yIY3VHfOHUd/Btg==
      TRANSFER_TOKEN_SALT: zLXkayR6XqbEN130yTMDaw==

      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      JWT_SECRET: 1+Nl3cItlLBrAVGDtKSp/g==
      NTBA_FIX_319: 1

      TELEGRAM_TOKEN: 7054787088:AAHd1-1UuWGTwYo3CBOvytMoACve3aGWrJY
      RESEND_API_KEY: re_i9tQfThW_QFc87jisdi8MvWkShrmXarfk
      RESEND_EMAIL: htz34@yandex.ru
      BACKEND_URL: https://xn--80ascqaidaiedd.xn--p1ai/backend
      BACKEND_TOKEN: dfa36a27ece762e5381584ba106650e9906cf06ed65cb6ad5000f54b4d68f7c48f4032ce64e04e2a693e11b587cff079761dcf5ac8cc3ea5f9f5c99894f83a7ff887f21c70ab31177d42c2c6ed23a2df8deb9e77bc3a47ae4cdc45b7fac1cefb5aa45c590732f7ef2ad01271db39d897f5fa3ba27c668a4466bd14b954c1bbfb
      FRONTEND_URL: http://frontend:3000
    ports:
      - "1337:1337"

networks:
  app-network:
    driver: bridge
