FROM node:18

# Server path
RUN mkdir -p /usr/src/backend
WORKDIR /usr/src/backend

# Copy package.json that holds our configuration
COPY ./package.json .

# Install local dependencies
RUN yarn install && yarn cache clean

#
COPY . .

#
EXPOSE 1337

# Run strapi in development mode
CMD NODE_ENV=development yarn develop